#!/usr/bin/env bash
# Autogenerated script, compiled from the Bish language.
# Bish version 0.1
# Please see https://github.com/tdenniston/bish for more information about Bish.

function bish_main () {
    mkdir build;
    stdlib_cd "$_0";
    cmake ../ -D CMAKE_INSTALL_PREFIX=".";
    make install;
    ./main;
}

function stdlib_cd () {
    local path="$1";
    cd $path;
}
args=( $0 "$@" );
_0="build";
bish_main;
